### ISSUE TITLE
Sandbox / Production environment verification

### ISSUE THREAD

**Issue by seagullua** [shoshins/apple-receipt#10]
The recommended way from Apple to verify receipts is to first try the production URL. If fails try sandbox URL. Details https://developer.apple.com/documentation/storekit/in-app_purchase/validating_receipts_with_the_app_store 

<img width="793" alt="Screen Shot 2021-03-29 at 8 38 20 PM" src="https://user-images.githubusercontent.com/759038/112925211-b9cfd400-90ce-11eb-8f2f-8bc3235d9adb.png">

It would be amazing to have mode Both, as now it is pretty hard to use the given approach.

**Comment by EbramTawfik** [comment]
@shoshins I had the same issue. The app will not be approved till the server supports (Sandbox and Production)

`When validating receipts on your server, your server needs to be able to handle a production-signed app getting its receipts from Apple’s test environment. The recommended approach is for your production server to always validate receipts against the production App Store first. If validation fails with the error code "Sandbox receipt used in production," you should validate against the test environment instead.`

I added a fix in my fork. https://github.com/EbramTawfik/apple-receipt

**Comment by shoshins** [comment]
Hi, @EbramTawfik . Thanks for reaching out. You can make Pull Request, it would be appreciated.

**Comment by shoshins** [comment]
<img width="798" alt="image" src="https://user-images.githubusercontent.com/5468795/116789537-046eb280-aab8-11eb-8434-4aa116ce3004.png">

I got Apple's point about Preview tests. But I think we cannot use it. This solution would contain a vulnerability. 

**Technically it would look like:**
```
var result = CheckProduction(incomeData)
if (result  = Test Data sent to Production) then 
var result = CheckSandbox(incomeData)
end if
return result
```

**And the vulnerability is:**
I (intruder) can send Sandbox information as incomeData into your Production server and the result will be "Success". Not only "when testing your app in the sandbox and while your application is in review." as Apple suggests but also at any time, even during "when your app is live in the App Store". Which, obviously, incorrect. Production shouldn't return Success using the Sandbox Apple server.

As for my opinion, **your server should determine** if the app is under review or testing rather than production response.
**For example:**
```
ICollection versionsUnderTest;
ICollection versionsUnderReview;
if (applicationVersion is in versionsUnderTest or applicationVersion is in versionsUnderReview) then 
verificatorService.SandBoxVerify(Data)
else
verificatorService.ProductionVerify(Data)
end if
```

Btw, you still can implement Apple's suggestion "(if TestReceiptOnProd) then checkSandbox" outside the library, in your server code. **But I don't recommend doing this.**

@EbramTawfik @seagullua what do you think about that?

UPD: v.2.2.0 now has more flexibility to choose Production/Sandbox. You have at least 3 options on how to use the Verifier. More Details inside Read.me & Tests.

**Comment by EbramTawfik** [comment]
@shoshins sorry I missed this notification. Do I need to create a pull request or you already did?

about 
`I (intruder) can send Sandbox information as incomeData into your Production server and the result will be "Success". Not only "when testing your app in the sandbox and while your application is in review." as Apple suggests but also at any time, even during "when your app is live in the App Store". Which, obviously, incorrect. Production shouldn't return Success using the Sandbox Apple server`

From where can intruder get a valid receipt? and I think even if he did it will be expired.

**Comment by shoshins** [comment]
Hi, @EbramTawfik. 

> Do I need to create a pull request or you already did?

Already did. You can find updates in versions upper than v.2.2.0 (2.2.1 is the most modern one)

> From where can intruder get a valid receipt? and I think even if he did it will be expired.

Yep, that's difficult to make preparations for such hacker activities. The intruder must spend some time thinking about how to use this opportunity. But the possibility is not perfect by itseft as for my opinion.

Btw, I've kept Apple's suggestion and our previous usage option possible. Everyone can choose an affordable way.

Here it is some examples:
https://github.com/shoshins/apple-receipt/blob/master/README.md#how-to-use-1
Usage options 1, 2 and 3.

**Comment by EbramTawfik** [comment]
Thanks @shoshins !
